### PR TITLE
airbrake_initializer: update blacklist_keys to the new API

### PR DESCRIPTION
**Pull request by kyrylo**
This should've been in airbrake-5.2.0, but I forgot to update it :(

### CODE REVIEW

**Comment by shifi** [comment]
LGTM

**Comment by hale** [comment]
Does the documentation need updating as well? https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md#library-api

**Comment by kyrylo** [comment]
@hale good catch. Updated in https://github.com/airbrake/airbrake/pull/553
Thanks!

**Comment by hale** [comment]
Great - thank you!


> On 20 May 2016, at 18:58, Kyrylo Silin <notifications@github.com> wrote:
> 
> @hale <https://github.com/hale> good catch. Updated in #553 <https://github.com/airbrake/airbrake/pull/553>
> Thanks!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub <https://github.com/airbrake/airbrake/pull/530#issuecomment-220675853>

--
  Philip Hale
  PG Hale Ltd.

  @  : philip@pghale.com
  UK : 07951650523

**Pull request merged**
