### PR TITLE
Make rack vars filters configurable

### PR DESCRIPTION
**Pull request by shifi**
Make rack vars filters configurable so users can replace or append to [default list](https://github.com/airbrake/airbrake/blob/master/lib/airbrake/utils/rack_filters.rb).

GH issue: #284 

New docs are ready once we push new gem release.

### CODE REVIEW

**Comment by vmihailenco** [comment]
What is the purpose of having separate sets of `:params_filters` and `:rack_filters`? Why `:params_filters` can't contain `:rack_filters`?

>New docs are ready once we push new gem release.

I would like to see docs - they could help me to understand this PR better.

**Comment by shifi** [comment]
It was like that before, I'm not sure why. We also have `rake_environment_filters` which are configurable but don't have default list, which I'm planning to fix to include default list of rack vars.
If we add default rack vars filters to default list of params filters, we could break current behaviour for users who use `config.params_filters = []` or similar.
That way, we wouldn't remove [any rack var from default list](https://github.com/airbrake/airbrake/blob/master/lib/airbrake/utils/rack_filters.rb), and everything would be sent to Airbrake. I think this is the most sensitive data which should be removed always.

>I would like to see docs - they could help me to understand this PR better.

[Docs](https://gist.github.com/shifi/049e3185771d02ac2d0f)

**Comment by vmihailenco** [comment]
I think that is fine. `config.params_filters = []` means that user does not want to use filters. So slightly changing behaviour regarding `rack_filters` seems fine to me.

Please merge :rack_filters into :params_filters and update changelog (do we have it?).

I also think that we should not touch `rake_environment_filters`, deprecate it and remove from the docs if it is documented.

**Comment by shifi** [comment]
@zefer thoughts?

**Comment by zefer** [comment]
I think we should put a hold on this, and rethink filtering as part of a new major release (`v5.0.0`) that will require a new configuration file format. It's time to tidy up this configuration to make it easier to understand. Something along these lines might work...

Use a *single* config variable to define *all* filters (for env vars, params, etc). Use a second config variable that specifies if this is a whitelist or a blacklist. It might look like below...

```rb
# Config defaults.
var_filters = %w[password password_confirmation]
var_filters_mode = :blacklist
```

**Comment by shifi** [comment]
:+1:

**Comment by shifi** [comment]
Although, there would be much more defaults. Current params filters default + rack vars filters default

**Pull request closed without merging**
