### PR TITLE
rack: add support for multiple notifiers

### PR DESCRIPTION
**Pull request by kyrylo**
Work in progress.

### CODE REVIEW

**Comment by kyrylo** [comment]
We couldn't figure out best way to implement this and [agreed to close this for now](https://github.com/airbrake/airbrake-ruby/pull/62#issuecomment-206788580).

**Comment by jonahx** [comment]
@kyrylo I may be missing something obvious, since I only just glanced at the source here:

https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rack/middleware.rb

but isn't it just a matter of:

1. passing the name of the config to the Middleware initializer, and saving that, say as `@config_name`.
2. changing line 24 to `notify_airbrake(ex, env, @config_name)`

Then in your sinatra app: `use Airbrake::Rack::Middleware, :some_config`

**Comment by kyrylo** [comment]
Your described scenario is achieved with this PR, but with a slightly different API. I like what you suggested more because `use Airbrake::Rack::Middleware, :some_config` seems to be simpler. It's been a while and I need to refresh my memory, so I am going to investigate this feature again and report back shortly.

**Comment by kyrylo** [comment]
@jonahx the support has been added. Could you please test this PR with your project and tell me if it meets your expectations?

**Comment by jonahx** [comment]
@kyrylo Thanks, this looks great!  Exactly what I wanted.

**Comment by AwolDes** [comment]
Closing the loop on this. Named notifiers were removed at some point: https://github.com/airbrake/airbrake-ruby/pull/493

**Pull request merged**
