### PR TITLE
rack: release active connection

### PR DESCRIPTION
**Pull request by kyrylo**
Similar to #562. We have to have this extra safety measure to ensure
we don't leak DB connections. More information:
https://blog.codefront.net/2009/06/15/activerecord-rails-metal-too-many-connections/

In normal Rails code we don't need to do that because Rails has a
[middleware][1] to deal with this issue. Our Rack middleware kicks in
earlier, so we have to deal with this on our own.

[1]: https://github.com/rails/rails/blob/107f4282bbfabc011d5ad3bcf3fb3c6fb812ad30/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L645

### CODE REVIEW

**Comment by vmihailenco** [comment]
>Our Rack middleware kicks in earlier, so we have to deal with this on our own.

Did you consider changing middleware order so Rack middleware can do its job?

**Comment by kyrylo** [comment]
Our middleware (and middleware of all other other similar libraries) has always been inserted after `DebugExceptions`. I cannot really tell the implications of inserting it a bit later, but here's the default Rails 4 middleware stack (with our library):

```
use Rack::Sendfile
use ActionDispatch::Static
use Rack::LiveReload
use Rack::Lock
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use Airbrake::Rack::Middleware
use ActionDispatch::RemoteIp
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Warden::Manager
use Rack::Cors
use CustomDomainCookie
run AirbrakeApp::Application.routes
```

So, if we're taking an alternative direction, we want to insert it after `ActiveRecord::ConnectionAdapters::ConnectionManagement`. It means that errors in these errors won't be caught:

* [ActionDispatch::RemoteIp](http://api.rubyonrails.org/classes/ActionDispatch/RemoteIp.html)
* [ActionDispatch::Reloader](http://api.rubyonrails.org/classes/ActionDispatch/Reloader.html)
* [ActionDispatch::Callbacks](http://api.rubyonrails.org/classes/ActionDispatch/Callbacks.html)

I feel a bit uneasy about changing order because I cannot really predict what will happen.

**Comment by vmihailenco** [comment]
Overall why we execute any SQL queries? Can we avoid it?

>I feel a bit uneasy about changing order because I cannot really predict what will happen.

Probably it will fix the issue. Probably not. Nothing dangerous.

**Comment by kyrylo** [comment]
We call `current_user`, which is a common, but not standard method in all Rails apps that have user profiles. Its implementation can be anything (a library might implement it, or the app itself), so sometimes it can execute SQL queries. Let's try changing the order, since I am not convinced about the current solution, too.

**Pull request closed without merging**
