### PR TITLE
[#419] don't fail on request param containing |

### PR DESCRIPTION
**Pull request by alexis779**
Replace URI.join

### CODE REVIEW

**Comment by kyrylo** [comment]
Hi, @alexis779!

Thanks for this PR, but I think it's better to `escape` fullpath like this:

```ruby
URI.join(url, URI.escape(request.fullpath)).to_s
```

Could you please confirm that this works for you?

I'd also be happy to see a test that tests `|`.

**Comment by kyrylo** [comment]
@alexis779 a gentle ping.

**Comment by alexis779** [comment]
The problem with URI.escape is that it modifies the input sent by the client. For example `|` is rewritten into `%7C`.
Feel free to adapt the PR if you have a good reason to keep that.

I added a unit test that, without the PR, fails with

```
Error: test: #airbrake_request_url should handle invalid character in param. (ControllerMethodsTest): URI::InvalidURIError: bad URI(is not URI?): path?name=|
/usr/lib/ruby/2.1.0/uri/generic.rb:1203:in `rescue in merge'
/usr/lib/ruby/2.1.0/uri/generic.rb:1200:in `merge'
/usr/lib/ruby/2.1.0/uri/common.rb:237:in `each'
/usr/lib/ruby/2.1.0/uri/common.rb:237:in `inject'
/usr/lib/ruby/2.1.0/uri/common.rb:237:in `join'
/usr/lib/ruby/2.1.0/uri/common.rb:785:in `join'
/home/alexis/job/airbrake/lib/airbrake/rails/controller_methods.rb:102:in `airbrake_request_url'
/home/alexis/job/airbrake/test/controller_methods_test.rb:135:in `block (2 levels) in <class:ControllerMethodsTest>'
/var/lib/gems/2.1.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `instance_exec'
/var/lib/gems/2.1.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `block in create_test_from_should_hash'
```

Better than a Newrelic screenshot ...


Also you can manually reproduce the error in a new Rails app adding `thin` (`webrick` would send a BadRequest) and `airbrake` in the Gemfile
```
gem 'thin'
gem 'airbrake'
```
with airbrake initializer `config/initializers/airbrake.rb`
```
Airbrake.configure do |config|
  config.api_key = '<KEY>'
end
```

**Comment by kyrylo** [comment]
I can see your point about the modified input. Thanks for the PR!

**Comment by kyrylo** [comment]
Sorry, I had to revert this change, because it fails our build. At the moment I cannot share the link to the failed build, but I'm resolving this now.

**Comment by kyrylo** [comment]
https://circleci.com/gh/airbrake/airbrake/314

**Pull request merged**
