### PR TITLE
Ignore RACK_ENV if it is empty (capistrano deploy), fixes #341.

### LINKED ISSUE #341: Deploy notifications go to wrong environment with Capistrano 2 when RACK_ENV not specified
Since upgrading to Airbrake gem 4.1.0 (from 3.1.16) in Sep 16, all my deploy notifications have gone to the Production environment, even if the environment was NOT Production.

This appears to be because after commit 5e50f6233bb5d82aa827fa2890d82deafa8f7d94 the RAILS_ENV value is effectively ignored.  RACK_ENV is used, or if missing, then "production".

### PR DESCRIPTION
**Pull request by oree**

### CODE REVIEW

**Comment by tmikoss** [comment]
+1, I was surprised by this when upgrading to airbrake 4

**Comment by ebeigarts** [comment]
:+1:

**Comment by teknull** [comment]
+1

**Comment by Zelnox** [comment]
+1

**Comment by shifi** [comment]
@oree thank you for this PR!

**Pull request merged**
