### PR TITLE
fixes: #try_current_user when controller#current_user is private

### PR DESCRIPTION
**Pull request by krisleech**
fixes: #try_current_user fails to get user when controller#current_user is a private method

### CODE REVIEW

**Comment by kyrylo** [comment]
This is awesome, thanks! Would you mind adding a test?

**Comment by krisleech** [comment]
No problem, I can't get the specs to run:

```
be rspec    
################################################################################
# RUBY_VERSION: 2.3.1
# RUBY_ENGINE: ruby
# Rack release: 1.6.5
################################################################################
bundler: failed to load command: rspec (/home/kris/.gem/ruby/2.3.1/bin/rspec)
NameError: uninitialized constant Warden
  /home/kris/dev/airbrake/spec/integration/shared_examples/rack_examples.rb:2:in `block in <top (required)>'
```

I'll take a look further later on.

**Comment by kyrylo** [comment]
You don't need to run the whole test suite because it takes a while. You want to run this:

```sh
bundle exec rspec spec/unit/rack/user_spec.rb
```

**Comment by kyrylo** [comment]
👍

**Comment by krisleech** [comment]
Test added and I can confirm, after deploying this same commit cherry picked on top of tag v5.7.1, that it works.

**Comment by krisleech** [comment]
:+1:

**Pull request merged**
