### PR TITLE
Use bundle exec rake in capistrano 3 task

### LINKED ISSUE #563: Capistrano deploy notification with multiple rake installs
I get this error:
> Gem::LoadError: You have already activated rake 10.4.2, but your Gemfile requires rake 11.1.2. Prepending `bundle exec` to your command may solve this.

Is it intentional that the gem does not use `bundle exec rake`:
https://github.com/airbrake/airbrake/blob/master/lib/airbrake/capistrano/tasks.rb#L10

Do I have to use [capistrano/bundler](https://github.com/capistrano/bundler/) to make it work?

### PR DESCRIPTION
**Pull request by fsmanuel**
closes #563

### CODE REVIEW

**Comment by kyrylo** [comment]
👍

**Comment by fsmanuel** [comment]
Thanks! Will there be a bugfix release or should I use master?

**Comment by kyrylo** [comment]
I'll release it today and ping you.

**Comment by kyrylo** [comment]
I just released v5.4.1. Thanks for the fix!

**Pull request merged**
