### PR TITLE
add support for sidekiq 7

### PR DESCRIPTION
**Pull request by roman-melnyk**

### CODE REVIEW

**Comment by roman-melnyk** [comment]
@kyrylo could you please review?

**Comment by roman-melnyk** [comment]
@nick-desteffen ?

**Comment by nick-desteffen** [comment]
@roman-melnyk I don't maintain this repo

**Review by mmcdaris — APPROVED** [review]
Nice fix, I've confirmed this is needed for SideKiq 7 support, Thank you for your contribution, your work will be included in the next release.

**Pull request merged**
