### PR TITLE
README: add a screenshot of the dashboard

### PR DESCRIPTION
**Pull request by kyrylo**

### CODE REVIEW

**Comment by phumpal** [comment]
A minor nitpick - can we move the screenshot to cloudfront or even just s3?

**Comment by kyrylo** [comment]
Sure, updated (and moved all the screenshots to S3). PTAL

**Comment by phumpal** [comment]
LGTM

**Comment by zefer** [comment]
Looks like you missed moving the dashboard image. Otherwise, LGTM.

**Comment by kyrylo** [comment]
My bad, fixed.

**Pull request merged**
