### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by markburns**
This tackles some of the largest issues highlighted in code climate.

https://codeclimate.com/github/airbrake/airbrake/Airbrake::Notice

Brings this class up from an F to a B.
https://codeclimate.com/github/markburns/airbrake/lib/airbrake/notice.rb?from_sha=68bec497&to_sha=1e706a9f

Overall score goes from 2.83 to 3.66 GPA

### CODE REVIEW

**Comment by kyrylo** [comment]
Hello! Thanks for your PR! 

I am looking at this counter `+262 −152` and the changes, and I must say I'm not sure I catch the goal of this refactoring. Yes, the CodeClimate score may be improved, but now it's much harder to support and understand the code after the presented changes. The PR adds 3 new classes, defines inheritance, scatters the code across multiple files, defines helper methods and defines 1 factory method. We also use complex metaprogramming techniques now. This looks a lot more complex than just defining things inline.

I believe it's better to keep it simple, even for the sake of the CodeClimate score.

**Comment by markburns** [comment]
That's one way of thinking of clearer separation of concerns, shorter methods and general reduction in cyclomatic complexity. If you find this code harder to read than the original then I won't try to convince you that it is better.

**Comment by kyrylo** [comment]
@markburns I am very sorry, I appreciate your work. In my opinion the main problem is not solved. The render methods are still huge. That's the real problem.

**Comment by markburns** [comment]
I'd say that the render methods and any other DSL that represents data can be considered a valid place for ignoring cyclomatic complexity, hence the refactor and `.codeclimate.yml` ignore. 
They are effectively views or templates. I don't see how this _doesn't_ solve that issue as that's specifically what I tackled. Unless you don't like to consider them as view-like objects.

I think our style of coding and ways of thinking about what constitutes readable, maintainable code are coming from completely different ways of thinking and I can't empathise with yours, so I can't really contribute anything.

**Pull request closed without merging**
