### PR TITLE
If we cannot stringify then at least rescue the dup exceptions ...

### PR DESCRIPTION
**Pull request by grosser**
followup to https://github.com/airbrake/airbrake/pull/328

now I ran into a Rack::Session::Abstract::SessionHash with symbol keys -> kaboom again ...

@shifi @dvdplm

### CODE REVIEW

**Comment by sandlerr** [comment]
@dvdplm can this be released please? We'd prefer not to depend on this gem off a git repo.

**Comment by grosser** [comment]
@dvdplm can you make a new release ?

**Comment by grosser** [comment]
@dvdplm can you release please ?

**Comment by mmcdaris** [comment]
I just brought this up to the team, thanks for the pings!

**Comment by sandlerr** [comment]
@grosser 4.2.0 includes this

**Comment by grosser** [comment]
already got us updated :D

**Pull request merged**
