### PR TITLE
notice_builder: support class definitions for builders

### PR DESCRIPTION
**Pull request by kyrylo**
Also:

  * add optional default builder - `RequestBodyBuilder` (appends request
    body)
  * refactor other builders, so they also use classes

### CODE REVIEW

**Comment by vmihailenco** [comment]
Why we have both notice filters `airbrake.add_filter` and notice rack builders `airbrake.add_rack_builder`?

**Comment by kyrylo** [comment]
Rack builders have access to the `request` object, `add_filter` can't have such access.

**Comment by vmihailenco** [comment]
That answer tells me nothing and is also just not very accurate. Rack, not rack builder, has access to request. And if you want to let filters access to request you can just pass it to them

```
notice = Notice.new
notice.request = @request
@apply_filters(notice)
```

**Comment by kyrylo** [comment]
I see your point. Currently, with your proposal, `notice.to_json` will contain a lot of garbage from `request`. I could try to get rid of `add_rack_builder` and use `add_filter`, however we need to design this a bit better.

What do you think of having a special key, which would hold all custom objects available to filters. When filtering is done, we remove that key from the notice, so it doesn't affect the payload.

For example:

```rb
notice = Notice.new
notice[:objects][:request] = request

Airbrake.add_filter do |notice|
  notice[:session] = notice[:objects][:request][:session]
end

def apply_filters(notice)
  # applied filters here

  notice.delete(:objects)
end
```

**Comment by vmihailenco** [comment]
Looks like it already ignores unknown fields on notice - https://github.com/airbrake/airbrake-ruby/blob/master/lib/airbrake-ruby/notice.rb#L79-L91. But some special field sounds good too.

**Comment by kyrylo** [comment]
Closed in favour of https://github.com/airbrake/airbrake/pull/654.

**Pull request closed without merging**
